{
 "title": "Utility Meters",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Gas flow [10m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "expr": "rate(utility_sensor{type=\"gas\"}[10m]) / 100"
    }
   ]
  },
  {
   "title": "Gas usage in time range",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(utility_sensor{type=\"gas\"}[$__range]) / 100"
    }
   ]
  },
  {
   "title": "Gas total counter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "expr": "utility_sensor{type=\"gas\"} / 100"
    }
   ]
  }
 ]
}