name: Deployment

concurrency: production

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deployment:
    # The type of runner that the job will run on
    runs-on: self-hosted
    environment: production

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Copy sources
        run: rsync -av --delete --exclude=".*" . /home/pi/smartmeter/
      
      - name: Install dependencies
        run: cd /home/pi/smartmeter/ && export CFLAGS=-fcommon && pipenv install --deploy
